# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "4.2"

version: "{build}-{branch}"

init:
  - git config --global core.longpaths true

clone_depth: 1

matrix:
  fast_finish: true

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - appveyor DownloadFile "http://downloads.sourceforge.net/project/graphicsmagick/graphicsmagick-binaries/1.3.24/GraphicsMagick-1.3.24-Q16-win64-dll.exe?r=&ts=1470470434&use_mirror=kent"
  - GraphicsMagick-1.3.24-Q16-win64-dll.exe /SP /VERYSILENT /NORESTART /NOICONS /DIR=%CD%\gm
  - set PATH=%CD%\gm;%PATH%
  - npm install

test_script:
  - node --version
  - npm --version
  - gm version
  - npm run lint
  - npm test

build: off
