# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: "10"

version: "{build}-{branch}"

init:
  - git config --global core.longpaths true

clone_depth: 1

matrix:
  fast_finish: true

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - appveyor DownloadFile "https://downloads.sourceforge.net/project/graphicsmagick/graphicsmagick-binaries/1.3.34/GraphicsMagick-1.3.34-Q16-win64-dll.exe"
  - GraphicsMagick-1.3.34-Q16-win64-dll.exe /SP /VERYSILENT /NORESTART /NOICONS /DIR=%CD%\gm
  - set PATH=%CD%\gm;%PATH%
  - npm install

before_test:
  - node --version
  - npm --version
  - gm version

test_script:
  - npm run lint
  - npm test

after_test:
  - node bin/shigehachi.js -P tests/fixtures/prev/ -C tests/fixtures/curr/ -O tests/fixtures/output -A -v
  - ls -lh tests/fixtures/output
  - cat tests/fixtures/output/shigehachi.json

build: off
