# http://www.appveyor.com/docs/appveyor-yml

image:
  - Visual Studio 2022

environment:
  NODE_SKIP_PLATFORM_CHECK: 1
  nodejs_version: "24"

version: "{build}-{branch}"

init:
  - git config --global core.longpaths true

clone_depth: 1

cache:
  - node_modules

# http://www.graphicsmagick.org/INSTALL-windows.html#retrieve-install-package
# https://sourceforge.net/projects/graphicsmagick/files/graphicsmagick-binaries/1.3.45/
install:
  - ps: Install-Product node $env:nodejs_version
  - appveyor DownloadFile "https://downloads.sourceforge.net/project/graphicsmagick/graphicsmagick-binaries/1.3.45/GraphicsMagick-1.3.45-Q8-win32-dll.exe"
  - GraphicsMagick-1.3.45-Q8-win32-dll.exe /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /NOICONS /DIR=%CD%\gm
  - set PATH=%CD%\gm;%PATH%
  - npm ci

before_test:
  - node --version
  - npm --version
  - gm version

test_script:
  - npm run lint
  - npm test

after_test:
  - node bin/shigehachi.js -P tests/fixtures/prev/ -C tests/fixtures/curr/ -O tests/fixtures/output -A -v
  - ls -lh tests/fixtures/output
  - cat tests/fixtures/output/shigehachi.json

build: off
